name: curserio
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - streamlit=1.52.2
  - numpy
  - ffmpeg
  - scipy
  - pip:
      - openai-whisper==20250625
      - torch
      - sounddevice==0.5.3
      - langdetect==1.0.9
      - panphon==0.22.2
      - hangul-romanize==0.1.0